version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-14-lein-2.9.1-buster

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"

    steps:
      - checkout
      - run: make all
