version: 2.1
variables:
  multi_hash_args:
    in-files: file1.txt file2.yml
    out-file: /tmp/infiles_checksum
    cache-prefix: dep-v1
  cache_name: 'maven-repo-v1-{{ .Branch }}-{{ checksum "/tmp/infiles_checksum" }}'
orbs:
  multi_file_hash_cache: cobli/multi-file-hash-cache@0.0.4
jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      AWS_REGION: "eu-west-1"
      AWS_ACCESS_KEY_ID: "localstack"
      AWS_SECRET_ACCESS_KEY: "localstack"

    steps:
      - checkout
      - multi_file_hash_cache/restore:
          in-files: ./mulog-kinesis/project.clj ./mulog-filesystem-metrics/project.clj ./mulog-elasticsearch/project.clj ./mulog-cloudwatch/project.clj ./mulog-json/project.clj ./mulog-zipkin/project.clj ./mulog-mbean-sampler/project.clj ./examples/usage/project.clj ./examples/roads-disruptions/project.clj ./mulog-slack/project.clj ./mulog-jvm-metrics/project.clj ./mulog-kafka/project.clj ./mulog-adv-console/project.clj ./mulog-core/project.clj ./mulog-prometheus/project.clj
          out-file: /tmp/infiles_checksum
          cache-prefix: maven-repo-v1

      - run: make all

      # don't cache local artifacts
      - run: rm -fr ~/.m2/repository/com/brunobonacci/

      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "/tmp/infiles_checksum" }}
          key: maven-repo-v1-{{ .Branch }}-
