version: '3'
services:

  zookeeper:
    # image: wurstmeister/zookeeper
    image: zookeeper:3.5.5
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: <your-local-ip>
      KAFKA_CREATE_TOPICS: "mulog:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
